[package]

name = "simple-link-test"
version = "0.1.0"
authors = ["Travis Finkenauer <tmfinken@gmail.com>"]
license = "MIT"
readme = "README.md"
description = "simple linking test"
edition = "2021"

[build-dependencies]
cc = "1"
